### PR TITLE
Providing access to script/launch file

### PR DESCRIPTION
**Pull request by pankajv82**
We are facing issues while running image built using dockerfile. It fails with permission error. Everything works fine after adding below line. 

RUN chmod u+x ${APP_HOME}/script/launch

### CODE REVIEW

**Comment by unleashed** [comment]
Hi @pankajv82, thanks for the patch.

I am curious as to what's the setup you are using for building the docker image. Which versions of docker, git and operating system are you using? I suspect the checkout of the repository might not properly preserve the execution bit mode for the scripts in your environment.

Regardless the patch is ok, so I am applying it.

**Comment by unleashed** [comment]
Does the patch in https://github.com/3scale/xcflushd/commit/9dc9bced21682f36244801933d11cd78e5d19bf9 work for you?

**Comment by pankajv82** [comment]
We are using Centos 7. We have jenkins job which builds image from this repository.

**Comment by unleashed** [comment]
@pankajv82 I understand the proposed patch in https://github.com/3scale/xcflushd/pull/35#issuecomment-313384926 works for you - will merge tomorrow if there's no confirmation.

**Comment by pankajv82** [comment]
Yes, PATH works. :+1:

**Pull request closed without merging**
